Feature/tasks
Leenday/task_manager pull request #18
Opened 2022-12-17 10:14 UTC by Leenday

2022-12-19 07:39 UTC, greybutton requested changes

2022-12-19 07:39 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    params['task']['author_id'] = current_user.id
это зачем?

2022-12-19 07:39 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = 'id desc' if search.sorts.empty?
лучше с фронта сортировку задать. в контроллере не надо хардкодить

2022-12-19 07:39 UTC, greybutton commented on app/javascript/packs/components/TaskBoard/TaskBoard.js
> +import TasksRepository from 'repositories/TasksRepository';
1 смешались импорты пакетов и локальных файлов
2 `from 'forms/TaskForm';` с остальными по аналогии

2022-12-19 07:39 UTC, greybutton commented on config/routes.rb
> +      resources :tasks, only: %i[index show create update destroy], defaults: {format: 'json'}
`defaults: {format: 'json'}` на неймспейс апи сделать

2022-12-19 07:39 UTC, greybutton commented on package.json
> +    "ramda": "^0.28.0",
пакета qs не хватает

2022-12-19 07:39 UTC, greybutton commented on utils/fetchHelper.js
> +import axios from 'axios';
этот файл в папке жс должен быть

2022-12-19 07:39 UTC, greybutton commented on utils/keysConverter.js
> +import humps from 'humps';
этот тоже в жс папке

2022-12-19 09:41 UTC, Leenday commented on app/controllers/api/v1/tasks_controller.rb
> +    params['task']['author_id'] = current_user.id
Без этого, не создаются таски из-за отсутствия айди автора:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/47002584/208395391-87bf846c-d1d0-40d9-a630-003f1fefa2fb.png">

2022-12-19 12:28 UTC, Leenday commented
Еще вопрос по билду:

Как можно ошибку победить? Точнее - в чем причина? Конфиг надо править?

```
curl: (22) The requested URL returned error: 500
Warning: Problem : HTTP error. Will retry in 1 seconds. 12 retries left.
```

2022-12-19 18:30 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    params['task']['author_id'] = current_user.id
мы же передаем author_id

2022-12-19 18:31 UTC, greybutton commented
по ошибке 500, не понял когда она происходит

2022-12-20 05:52 UTC, Leenday commented on app/controllers/api/v1/tasks_controller.rb
> +    params['task']['author_id'] = current_user.id
Мб я что-то пропустил.
В логах при создании таски вот такие параметры:
```
web_1  | Started POST "/api/v1/tasks" for 172.30.0.1 at 2022-12-20 05:49:17 +0000
web_1  | Cannot render console from 172.30.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1  | Processing by Api::V1::TasksController#create as JSON
web_1  |   Parameters: {"task"=>{"name"=>"fdas", "description"=>"asdf", "assignee_id"=>nil, "author_id"=>nil}}
web_1  |   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
web_1  |   ↳ app/controllers/concerns/auth_helper.rb:21:in `current_user'
```

В следующем блоке точно передаются, если из селекта выбрать автора, а в противном случае тоже nil.

2022-12-20 05:53 UTC, Leenday commented
> по ошибке 500, не понял когда она происходит

Это по билдам при пуше ветки.
https://github.com/Leenday/task_manager/actions/runs/3731373066/jobs/6329598896

2022-12-22 06:00 UTC, greybutton approved these changes
насчет 500, у тебя уфизи файлы немного отличаются от примера, может из за этого не срабатывает уфизи деплой

2022-12-22 06:00 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    params['task']['author_id'] = current_user.id
странно 🤔 ну ладно

2022-12-22 06:05 UTC, merged