Feature/assignee
Leenday/task_manager pull request #19
Opened 2022-12-20 07:54 UTC by Leenday

2022-12-20 07:57 UTC, Leenday commented
В этой ветке присутствуют изменения из [feature/tasks](https://github.com/Leenday/task_manager/pull/18), т.к. последняя не влита, на момент формирования ПР, а изменения из нее необходимы для дальнейшей разработки.

2022-12-22 06:01 UTC, greybutton requested changes
реквест содержит код от другой задачи

2022-12-22 18:14 UTC, greybutton requested changes
презентеры нужно использовать во всем проекте

2022-12-22 18:14 UTC, greybutton commented on app/javascript/packs/components/Task/Task.js
> +// Task.propTypes = TaskPresenter.shape();
если код не нужен, то он удаляется, а не комментируется

2022-12-22 18:14 UTC, greybutton commented on app/javascript/packs/components/Task/Task.js
> -  onClick: PropTypes.func.isRequired,
почему удалил onClick?

2022-12-22 18:14 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    params.require(:task).permit(:id, :name, :description, :author_id, :assignee_id, :state_event, :expired_at)
почему ид добавил?

2022-12-23 07:31 UTC, Leenday commented on app/controllers/api/v1/tasks_controller.rb
> +    params.require(:task).permit(:id, :name, :description, :author_id, :assignee_id, :state_event, :expired_at)
Из-за ошибки при обновлении таски:
```
web_1  | Started PUT "/api/v1/tasks/60" for 172.30.0.1 at 2022-12-23 07:28:56 +0000
web_1  | Cannot render console from 172.30.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1  | Processing by Api::V1::TasksController#update as JSON
web_1  |   Parameters: {"task"=>{"id"=>60, "name"=>"fdsaf", "description"=>"asdfa", "assignee_id"=>4, "author_id"=>2}, "id"=>"60"}
web_1  |   Task Load (0.7ms)  SELECT "tasks".* FROM "tasks" WHERE "tasks"."id" = $1 LIMIT $2  [["id", 60], ["LIMIT", 1]]
web_1  |   ↳ app/controllers/api/v1/tasks_controller.rb:27:in `update'
web_1  | Unpermitted parameter: :id
```

2022-12-23 07:32 UTC, Leenday commented on app/javascript/packs/components/Task/Task.js
> -  onClick: PropTypes.func.isRequired,
Из-за `isRequired` была ошибка о том, что функция - undefined. Сейчас вернул без нее, ошибка ушла.

2022-12-23 07:32 UTC, Leenday commented on app/javascript/packs/components/Task/Task.js
> +// Task.propTypes = TaskPresenter.shape();
Удалил, спасибо

2022-12-26 07:51 UTC, greybutton requested changes
презентеры это про сущности в проекте, а не про пропсы компонентов. К юзерам и таскам во всем проекте применить презентеры, пропсы вернуть как было

2022-12-26 16:51 UTC, greybutton approved these changes

2022-12-26 18:10 UTC, merged