adds a rollbar to rails
Leenday/task_manager pull request #27
Opened 2022-12-28 12:31 UTC by Leenday

2022-12-29 06:37 UTC, greybutton requested changes

2022-12-29 06:37 UTC, greybutton commented on app/forms/session_form.rb
> +      Rollbar.error("email or password doesn't match")
роллбар не для логгирования валидаций

2022-12-29 06:37 UTC, greybutton commented on config/initializers/rollbar.rb
> +  config.access_token = Rails.application.credentials.dig(:rollbar, :access_token)
давай лучше через переменные окружения (environment variables) сделаем

2022-12-29 07:11 UTC, Leenday commented on config/initializers/rollbar.rb
> +  config.access_token = Rails.application.credentials.dig(:rollbar, :access_token)
А где правильно хранить переменные окружения в проекте?
.env, насколько я понимаю, не подходит.

2022-12-29 16:13 UTC, greybutton commented on config/initializers/rollbar.rb
> +  config.access_token = Rails.application.credentials.dig(:rollbar, :access_token)
реальные в github secrets, для разработки в композе файле фейковую строчку задать

2023-01-09 19:38 UTC, greybutton approved these changes

2023-01-10 06:10 UTC, merged