Feature/state machine
Leenday/task_manager pull request #7
Opened 2020-10-13 19:05 UTC by Leenday

2020-10-19 11:43 UTC, Andrew8xx8 requested changes

2020-10-19 11:43 UTC, Andrew8xx8 commented on app/models/task.rb
> +  state_machine initial: :new_task do
Нужно описать все можные стейты используя `state :some_state`

2020-10-22 20:58 UTC, Leenday commented on app/models/task.rb
> +  state_machine initial: :new_task do
Благодарю, добавил все стейты

2020-11-03 18:44 UTC, greybutton approved these changes

2020-11-05 18:59 UTC, greybutton commented on Gemfile
> +  gem 'state_machines-activerecord'
не в ту группу добавил, это гем не только в девелопе и тестах нужен, он общий

2020-11-16 19:30 UTC, Leenday commented on Gemfile
> +  gem 'state_machines-activerecord'
Вынес в общую группу, благодарю

2020-11-16 19:41 UTC, merged